<?php

include 'INC/session.php';

include 'INC/include.php';

$title = "MOTP-AS - About";
include 'INC/header.php';

$bcs = array ( array("index.php","home"), array("about.php","About") );

?>

<h1>Credits</h1>

<div class="stat">
<div>Most important:</div>
<ul>
<li>Thanks to Matthias for creating <a href="http://motp.sf.net/">Mobile OTP</a></li>
</ul>
</div>

<div class="stat">
<div>MOTP-AS:</div>
<ul>
<li>Adrian - logos and HTML layout</li>
<li>Jon - testing, texts and support</li>
<li>Sebastian - hacking and pre-build images</li>
<li>Steffen - maintaining and hosting web site</li>
</ul>
</div>

<div class="stat">
<div>Attributions:</div>
<ul>
<li>Menu was generated by <a href="http://purecssmenu.com/">Pure CSS Menu.com</a>.</li>
<li>Selecting dates is powered by <a href="http://www.rainforestnet.com/datetimepicker/datetimepicker.htm">JavaScript Date Time Picker</a>.</li>
<li>Some Icons are Copyright &copy; <a href="http://p.yusukekamiyamane.com/">Yusuke Kamiyamane</a>. All rights reserved. Licensed under a <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 license</a>.</li>
<li>Other Icons are from <a href="http://www.icojoy.com/">www.icojoy.com</a> | Zhebrakov Andrew (Andy-S).</li>
<li>HTML client generates passcodes using <a href="http://pajhome.org.uk/crypt/md5">md5.js</a>.</li>
<li>Tables can be sorted using <a href="http://www.kryogenix.org/code/browser/sorttable/">SortTable</a> by  Stuart Langridge.</li>
</ul>
</div>

<div class="stat">
<div>Thanks to:</div>
<ul>
<li>all, who wrote nice and friendly mails ;-)</li>
</ul>
</div>


<?php
include 'INC/footer.php';
?>
