<?php


/*** write to config file

	config file = RADIUS_CONF_CLIENTS
	format = 
		client 1.2.3.4 {
 			secret = client_shared_secret
 			shortname = name_from_database
		}

***/


function rad_save_write () {
	if ( (! RADIUS_CONF_CLIENTS) || (RADIUS_CONF_CLIENTS == "") ) return;

	$rclients = get_radclient_list ();

	$fp = fopen ( RADIUS_CONF_CLIENTS, "w" );
	if (! $fp) {
		echo "Cannot write RADIUS client config file " . RADIUS_CONF_CLIENTS . "!";
		return;
	}


	// write header 
	$header = "## DO NOT EDIT!\n## This file was automatically generated by MOTP-AS\n\n";
	fwrite ($fp, $header);

	foreach ($rclients as $rclient) {
		if (!$rclient->enabled) continue;
		// write client entry
		$entry = "client $rclient->ip {\n\tsecret = $rclient->secret\n\tshortname = $rclient->name\n}\n\n";
		fwrite ($fp, $entry);
	}
}


function rad_save_reload () {
	/* reload freeradius */

	if ( (! RADIUS_SERV_RELOAD) || (RADIUS_SERV_RELOAD == "") ) return;

	exec(RADIUS_SERV_RELOAD);
}


function rad_save () {
	rad_save_write();
	rad_save_reload();
}

?>
